version: "3"
services:
  nginx:
    container_name: nginx_forboot
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf # nginx 설정 파일 volume 맵핑
  docker-springboot:
    container_name: springboot_test
    build: .
    expose:
      - 8083
  
